<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MenusTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $menus = [
            [
                'id' => 1,
                'location' => 'header',
                'title' => 'Home',
                'title_hi' => 'होम',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/',
                'icon_png' => 'home',
                'parent_id' => null,
                'order' => 0,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 29, 23, 26, 52),
                'updated_at' => Carbon::create(2025, 12, 4, 22, 22, 28),
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'location' => 'header',
                'title' => 'About Us',
                'title_hi' => 'हमारे बारे में',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/about',
                'icon_png' => 'info',
                'parent_id' => null,
                'order' => 1,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 29, 23, 27, 48),
                'updated_at' => Carbon::create(2025, 12, 4, 22, 49, 1),
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'location' => 'header',
                'title' => 'Regulations',
                'title_hi' => 'नियम',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/standards',
                'icon_png' => 'fileCheck',
                'parent_id' => null,
                'order' => 2,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 29, 23, 28, 21),
                'updated_at' => Carbon::create(2025, 12, 4, 22, 50, 17),
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'location' => 'header',
                'title' => 'Activities',
                'title_hi' => 'गतिविधियाँ',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/activities',
                'icon_png' => 'ChartColumnIncreasing',
                'parent_id' => null,
                'order' => 3,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 29, 23, 29, 40),
                'updated_at' => Carbon::create(2025, 12, 4, 22, 32, 28),
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'location' => 'header',
                'title' => 'Environmental Data',
                'title_hi' => 'पर्यावरण डेटा',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/data',
                'icon_png' => 'CloudUploadIcon',
                'parent_id' => null,
                'order' => 4,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 29, 23, 30, 41),
                'updated_at' => Carbon::create(2025, 12, 4, 22, 51, 26),
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'location' => 'header',
                'title' => 'Laboratories',
                'title_hi' => 'प्रयोगशालाएँ',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/laboratories',
                'icon_png' => 'FlaskConical',
                'parent_id' => null,
                'order' => 5,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 29, 23, 31, 52),
                'updated_at' => Carbon::create(2025, 12, 4, 22, 52, 32),
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'location' => 'header',
                'title' => 'Recruitment',
                'title_hi' => 'भर्ती',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/job',
                'icon_png' => 'userCheck',
                'parent_id' => null,
                'order' => 7,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 29, 23, 32, 56),
                'updated_at' => Carbon::create(2025, 12, 4, 22, 57, 24),
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'location' => 'header',
                'title' => 'Tenders',
                'title_hi' => 'निविदाएँ',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/tenders',
                'icon_png' => 'Handshake',
                'parent_id' => null,
                'order' => 6,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 29, 23, 36, 29),
                'updated_at' => Carbon::create(2025, 12, 4, 22, 57, 10),
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'location' => 'header',
                'title' => 'Contact Us',
                'title_hi' => 'संपर्क',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/contact',
                'icon_png' => 'Phone',
                'parent_id' => null,
                'order' => 8,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 29, 23, 37, 21),
                'updated_at' => Carbon::create(2025, 12, 4, 22, 59, 31),
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'location' => 'header',
                'title' => 'Overview',
                'title_hi' => 'समीक्षा',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/about',
                'icon_png' => 'BookOpen',
                'parent_id' => 2,
                'order' => 0,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 29, 23, 42, 31),
                'updated_at' => Carbon::create(2025, 12, 10, 6, 39, 34),
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'location' => 'header',
                'title' => 'Functions',
                'title_hi' => 'कार्य',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/about/functions',
                'icon_png' => 'Layers',
                'parent_id' => 2,
                'order' => 1,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 29, 23, 43, 17),
                'updated_at' => Carbon::create(2025, 12, 10, 6, 39, 48),
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'location' => 'header',
                'title' => 'Structure',
                'title_hi' => 'संरचना',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/about/structure',
                'icon_png' => 'Layers',
                'parent_id' => 2,
                'order' => 3,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 29, 23, 43, 57),
                'updated_at' => Carbon::create(2025, 12, 10, 6, 40, 20),
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'location' => 'header',
                'title' => 'Members',
                'title_hi' => 'सदस्य',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/about/members',
                'icon_png' => 'Users',
                'parent_id' => 2,
                'order' => 2,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 29, 23, 55, 51),
                'updated_at' => Carbon::create(2025, 12, 10, 6, 40, 4),
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'location' => 'header',
                'title' => 'Who is Who',
                'title_hi' => 'प्रमुख व्यक्ति',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '#',
                'icon_png' => 'UserCircle',
                'parent_id' => 2,
                'order' => 4,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 0, 22),
                'updated_at' => Carbon::create(2025, 12, 15, 12, 17, 46),
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'location' => 'header',
                'title' => 'Head Office',
                'title_hi' => 'मुख्यालय',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/about/head-office',
                'icon_png' => 'Building2',
                'parent_id' => 17,
                'order' => 0,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 29, 23, 57, 30),
                'updated_at' => Carbon::create(2025, 12, 10, 6, 40, 48),
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'location' => 'header',
                'title' => 'Regional Directorates',
                'title_hi' => 'क्षेत्रीय निदेशालय',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/about/regional-directorates',
                'icon_png' => 'MapPin',
                'parent_id' => 17,
                'order' => 1,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 29, 23, 59, 0),
                'updated_at' => Carbon::create(2025, 12, 10, 6, 41, 55),
                'deleted_at' => null,
            ],

            [
                'id' => 18,
                'location' => 'header',
                'title' => 'Member Secretary\'s Message',
                'title_hi' => 'सदस्य सचिव का संदेश',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/about/messages/member-secretary',
                'icon_png' => 'Mail',
                'parent_id' => 40,
                'order' => 1,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 2, 0),
                'updated_at' => Carbon::create(2025, 12, 10, 6, 43, 16),
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'location' => 'header',
                'title' => 'Air Quality',
                'title_hi' => 'Air Quality',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/standards/air',
                'icon_png' => null,
                'parent_id' => 3,
                'order' => 0,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 4, 52),
                'updated_at' => Carbon::create(2025, 5, 30, 0, 4, 52),
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'location' => 'header',
                'title' => 'Water Quality',
                'title_hi' => 'Water Quality',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/standards/water',
                'icon_png' => null,
                'parent_id' => 3,
                'order' => 1,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 5, 19),
                'updated_at' => Carbon::create(2025, 5, 30, 0, 5, 19),
                'deleted_at' => null,
            ],
            [
                'id' => 21,
                'location' => 'header',
                'title' => 'Noise Standards/Rules',
                'title_hi' => 'Noise Standards/Rules',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/standards/noise',
                'icon_png' => null,
                'parent_id' => 3,
                'order' => 2,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 6, 43),
                'updated_at' => Carbon::create(2025, 10, 28, 13, 27, 35),
                'deleted_at' => null,
            ],
            [
                'id' => 22,
                'location' => 'header',
                'title' => 'Waste Management',
                'title_hi' => 'Waste Management',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/standards/waste',
                'icon_png' => null,
                'parent_id' => 3,
                'order' => 3,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 7, 29),
                'updated_at' => Carbon::create(2025, 5, 30, 0, 7, 29),
                'deleted_at' => null,
            ],
            [
                'id' => 23,
                'location' => 'header',
                'title' => 'Monitoring',
                'title_hi' => 'Monitoring',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/activities/monitoring',
                'icon_png' => null,
                'parent_id' => 4,
                'order' => 0,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 9, 9),
                'updated_at' => Carbon::create(2025, 5, 30, 0, 9, 9),
                'deleted_at' => null,
            ],
            [
                'id' => 24,
                'location' => 'header',
                'title' => 'Research',
                'title_hi' => 'Research',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/activities/research',
                'icon_png' => null,
                'parent_id' => 4,
                'order' => 1,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 9, 30),
                'updated_at' => Carbon::create(2025, 5, 30, 0, 9, 30),
                'deleted_at' => null,
            ],
            [
                'id' => 25,
                'location' => 'header',
                'title' => 'Training',
                'title_hi' => 'Training',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/activities/training',
                'icon_png' => null,
                'parent_id' => 4,
                'order' => 2,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 10, 2),
                'updated_at' => Carbon::create(2025, 5, 30, 0, 10, 2),
                'deleted_at' => null,
            ],
            [
                'id' => 26,
                'location' => 'header',
                'title' => 'Public Awareness',
                'title_hi' => 'Public Awareness',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/activities/public-awareness',
                'icon_png' => null,
                'parent_id' => 4,
                'order' => 3,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 10, 23),
                'updated_at' => Carbon::create(2025, 5, 30, 0, 10, 23),
                'deleted_at' => null,
            ],
            [
                'id' => 27,
                'location' => 'header',
                'title' => 'Air Quality',
                'title_hi' => 'Air Quality',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/data/air-quality',
                'icon_png' => null,
                'parent_id' => 5,
                'order' => 0,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 11, 50),
                'updated_at' => Carbon::create(2025, 5, 30, 0, 11, 50),
                'deleted_at' => null,
            ],
            [
                'id' => 28,
                'location' => 'header',
                'title' => 'Water Quality',
                'title_hi' => 'Water Quality',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/data/water-quality',
                'icon_png' => null,
                'parent_id' => 5,
                'order' => 1,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 12, 15),
                'updated_at' => Carbon::create(2025, 5, 30, 0, 12, 15),
                'deleted_at' => null,
            ],
            [
                'id' => 29,
                'location' => 'header',
                'title' => 'Noise Levels',
                'title_hi' => 'Noise Levels',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/data/noise-levels',
                'icon_png' => null,
                'parent_id' => 5,
                'order' => 2,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 12, 41),
                'updated_at' => Carbon::create(2025, 5, 30, 0, 12, 41),
                'deleted_at' => null,
            ],
            [
                'id' => 30,
                'location' => 'header',
                'title' => 'Air Lab',
                'title_hi' => 'Air Lab',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/laboratories/air-lab',
                'icon_png' => null,
                'parent_id' => 6,
                'order' => 0,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 13, 34),
                'updated_at' => Carbon::create(2025, 5, 30, 0, 13, 34),
                'deleted_at' => null,
            ],
            [
                'id' => 31,
                'location' => 'header',
                'title' => 'Water Lab',
                'title_hi' => 'Water Lab',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/laboratories/water-lab',
                'icon_png' => null,
                'parent_id' => 6,
                'order' => 1,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 13, 53),
                'updated_at' => Carbon::create(2025, 5, 30, 0, 13, 53),
                'deleted_at' => null,
            ],
            [
                'id' => 32,
                'location' => 'header',
                'title' => 'Bio Science Lab',
                'title_hi' => 'Bio Science Lab',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/laboratories/bio-science-lab',
                'icon_png' => null,
                'parent_id' => 6,
                'order' => 2,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 14, 18),
                'updated_at' => Carbon::create(2025, 5, 30, 0, 14, 18),
                'deleted_at' => null,
            ],
            [
                'id' => 33,
                'location' => 'header',
                'title' => 'Instrumentation Lab',
                'title_hi' => 'Instrumentation Lab',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/laboratories/instrumentation-lab',
                'icon_png' => null,
                'parent_id' => 6,
                'order' => 3,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 14, 48),
                'updated_at' => Carbon::create(2025, 5, 30, 0, 14, 48),
                'deleted_at' => null,
            ],
            [
                'id' => 34,
                'location' => 'header',
                'title' => 'NABL Quality Cell',
                'title_hi' => 'NABL Quality Cell',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/laboratories/nabl-quality-cell',
                'icon_png' => null,
                'parent_id' => 6,
                'order' => 4,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 16, 3),
                'updated_at' => Carbon::create(2025, 5, 30, 0, 16, 3),
                'deleted_at' => null,
            ],
            [
                'id' => 35,
                'location' => 'header',
                'title' => 'Trace Organics Lab',
                'title_hi' => 'Trace Organics Lab',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/laboratories/trace-organics-lab',
                'icon_png' => null,
                'parent_id' => 6,
                'order' => 5,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 16, 41),
                'updated_at' => Carbon::create(2025, 5, 30, 0, 16, 41),
                'deleted_at' => null,
            ],
            [
                'id' => 36,
                'location' => 'header',
                'title' => 'IT Lab',
                'title_hi' => 'IT Lab',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/laboratories/it-lab',
                'icon_png' => null,
                'parent_id' => 6,
                'order' => 6,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 17, 37),
                'updated_at' => Carbon::create(2025, 5, 30, 0, 17, 37),
                'deleted_at' => null,
            ],
            [
                'id' => 37,
                'location' => 'header',
                'title' => 'Recognition of Labs',
                'title_hi' => 'Recognition of Labs',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/laboratories/recognition-labs',
                'icon_png' => null,
                'parent_id' => 6,
                'order' => 7,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 0, 18, 35),
                'updated_at' => Carbon::create(2025, 5, 30, 0, 18, 35),
                'deleted_at' => null,
            ],
            [
                'id' => 38,
                'location' => 'inner-pages',
                'title' => 'Inner Pages',
                'title_hi' => 'Inner Pages',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => null,
                'icon_png' => null,
                'parent_id' => null,
                'order' => 0,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 5, 30, 4, 21, 35),
                'updated_at' => Carbon::create(2025, 5, 30, 4, 21, 35),
                'deleted_at' => null,
            ],
            [
                'id' => 39,
                'location' => 'header',
                'title' => 'Jurisdiction States',
                'title_hi' => 'Jurisdiction States',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/about/jurisdiction-states',
                'icon_png' => 'Map',
                'parent_id' => 17,
                'order' => 2,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 10, 6, 40, 16),
                'updated_at' => Carbon::create(2025, 12, 10, 6, 42, 10),
                'deleted_at' => null,
            ],
            [
                'id' => 40,
                'location' => 'header',
                'title' => 'Messages',
                'title_hi' => 'Messages',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '#',
                'icon_png' => 'MessageCircle',
                'parent_id' => 2,
                'order' => 5,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 10, 8, 49, 4),
                'updated_at' => Carbon::create(2025, 12, 15, 12, 17, 58),
                'deleted_at' => null,
            ],
            [
                'id' => 41,
                'location' => 'header',
                'title' => 'Chairman',
                'title_hi' => 'Chairman',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/about/messages/chairman',
                'icon_png' => 'User',
                'parent_id' => 40,
                'order' => 0,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 10, 8, 50, 3),
                'updated_at' => Carbon::create(2025, 12, 10, 6, 42, 40),
                'deleted_at' => null,
            ],
            [
                'id' => 42,
                'location' => 'footer-quickLink',
                'title' => 'About Us',
                'title_hi' => 'About Us',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/about',
                'icon_png' => null,
                'parent_id' => null,
                'order' => 0,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 11, 0, 54, 20),
                'updated_at' => Carbon::create(2025, 6, 11, 0, 54, 20),
                'deleted_at' => null,
            ],
            [
                'id' => 43,
                'location' => 'footer-quickLink',
                'title' => 'Acts & Rules',
                'title_hi' => 'Acts & Rules',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/acts-rules',
                'icon_png' => null,
                'parent_id' => null,
                'order' => 1,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 11, 0, 55, 5),
                'updated_at' => Carbon::create(2025, 6, 11, 0, 55, 5),
                'deleted_at' => null,
            ],
            [
                'id' => 44,
                'location' => 'footer-quickLink',
                'title' => 'Environmental Standards',
                'title_hi' => 'Environmental Standards',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/standards',
                'icon_png' => null,
                'parent_id' => null,
                'order' => 2,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 11, 0, 56, 6),
                'updated_at' => Carbon::create(2025, 6, 11, 0, 56, 6),
                'deleted_at' => null,
            ],
            [
                'id' => 45,
                'location' => 'footer-quickLink',
                'title' => 'Guidelines/SOPs',
                'title_hi' => 'Guidelines/SOPs',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/guidelines',
                'icon_png' => null,
                'parent_id' => null,
                'order' => 3,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 11, 0, 58, 7),
                'updated_at' => Carbon::create(2025, 6, 11, 0, 58, 7),
                'deleted_at' => null,
            ],
            [
                'id' => 46,
                'location' => 'footer-quickLink',
                'title' => 'Laboratories',
                'title_hi' => 'Laboratories',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/laboratories',
                'icon_png' => null,
                'parent_id' => null,
                'order' => 4,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 11, 0, 58, 46),
                'updated_at' => Carbon::create(2025, 6, 11, 0, 58, 46),
                'deleted_at' => null,
            ],
            [
                'id' => 47,
                'location' => 'footer-quickLink',
                'title' => 'Publications',
                'title_hi' => 'Publications',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/publications',
                'icon_png' => null,
                'parent_id' => null,
                'order' => 5,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 11, 0, 59, 10),
                'updated_at' => Carbon::create(2025, 6, 11, 0, 59, 10),
                'deleted_at' => null,
            ],
            [
                'id' => 48,
                'location' => 'footer-quickLink',
                'title' => 'Jobs',
                'title_hi' => 'Jobs',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/jobs',
                'icon_png' => null,
                'parent_id' => null,
                'order' => 6,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 11, 0, 59, 50),
                'updated_at' => Carbon::create(2025, 6, 11, 0, 59, 50),
                'deleted_at' => null,
            ],
            [
                'id' => 49,
                'location' => 'footer-quickLink',
                'title' => 'Tenders',
                'title_hi' => 'Tenders',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/tenders',
                'icon_png' => null,
                'parent_id' => null,
                'order' => 7,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 11, 1, 0, 14),
                'updated_at' => Carbon::create(2025, 6, 11, 1, 0, 14),
                'deleted_at' => null,
            ],
            [
                'id' => 50,
                'location' => 'footer-importantLink',
                'title' => 'RTI',
                'title_hi' => 'RTI',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/rti',
                'icon_png' => null,
                'parent_id' => null,
                'order' => 0,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 11, 1, 1, 1),
                'updated_at' => Carbon::create(2025, 6, 11, 1, 1, 1),
                'deleted_at' => null,
            ],
            [
                'id' => 51,
                'location' => 'footer-importantLink',
                'title' => 'Public Grievances',
                'title_hi' => 'Public Grievances',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/public-grievances',
                'icon_png' => null,
                'parent_id' => null,
                'order' => 1,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 11, 1, 1, 35),
                'updated_at' => Carbon::create(2025, 6, 11, 1, 1, 35),
                'deleted_at' => null,
            ],
            [
                'id' => 52,
                'location' => 'footer-importantLink',
                'title' => 'Disclaimer',
                'title_hi' => 'Disclaimer',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/disclaimer',
                'icon_png' => null,
                'parent_id' => null,
                'order' => 2,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 11, 1, 2, 45),
                'updated_at' => Carbon::create(2025, 6, 11, 1, 2, 45),
                'deleted_at' => null,
            ],
            [
                'id' => 53,
                'location' => 'footer-importantLink',
                'title' => 'Privacy Policy',
                'title_hi' => 'Privacy Policy',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/privacy-policy',
                'icon_png' => null,
                'parent_id' => null,
                'order' => 3,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 11, 1, 3, 18),
                'updated_at' => Carbon::create(2025, 6, 11, 1, 3, 18),
                'deleted_at' => null,
            ],
            [
                'id' => 54,
                'location' => 'footer-importantLink',
                'title' => 'Terms of Use',
                'title_hi' => 'Terms of Use',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/terms-of-use',
                'icon_png' => null,
                'parent_id' => null,
                'order' => 5,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 11, 1, 3, 47),
                'updated_at' => Carbon::create(2025, 6, 11, 1, 3, 47),
                'deleted_at' => null,
            ],
            [
                'id' => 55,
                'location' => 'footer-importantLink',
                'title' => 'Accessibility Statement',
                'title_hi' => 'Accessibility Statement',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/accessibility-statement',
                'icon_png' => null,
                'parent_id' => null,
                'order' => 5,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 11, 1, 7, 14),
                'updated_at' => Carbon::create(2025, 6, 11, 1, 7, 14),
                'deleted_at' => null,
            ],
            [
                'id' => 56,
                'location' => 'footer-importantLink',
                'title' => 'Screen Reader Access',
                'title_hi' => 'Screen Reader Access',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/screen-reader-access',
                'icon_png' => null,
                'parent_id' => null,
                'order' => 6,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 11, 1, 7, 31),
                'updated_at' => Carbon::create(2025, 6, 11, 1, 7, 31),
                'deleted_at' => null,
            ],
            [
                'id' => 57,
                'location' => 'footer-importantLink',
                'title' => 'Site Map',
                'title_hi' => 'Site Map',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/sitemap',
                'icon_png' => null,
                'parent_id' => null,
                'order' => 7,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 11, 1, 7, 55),
                'updated_at' => Carbon::create(2025, 6, 11, 1, 7, 55),
                'deleted_at' => null,
            ],
            [
                'id' => 58,
                'location' => 'footer-importantLink',
                'title' => 'Help',
                'title_hi' => 'Help',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/help',
                'icon_png' => null,
                'parent_id' => null,
                'order' => 8,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 11, 1, 8, 12),
                'updated_at' => Carbon::create(2025, 6, 11, 1, 8, 12),
                'deleted_at' => null,
            ],
            [
                'id' => 59,
                'location' => 'footer-importantLink',
                'title' => 'Contact Us',
                'title_hi' => 'Contact Us',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/contact',
                'icon_png' => null,
                'parent_id' => null,
                'order' => 8,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 11, 1, 8, 28),
                'updated_at' => Carbon::create(2025, 6, 11, 1, 8, 28),
                'deleted_at' => null,
            ],
            [
                'id' => 60,
                'location' => 'footer-importantLink',
                'title' => 'Feedback',
                'title_hi' => 'Feedback',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/feedback',
                'icon_png' => null,
                'parent_id' => null,
                'order' => 9,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 6, 11, 1, 8, 41),
                'updated_at' => Carbon::create(2025, 6, 11, 1, 8, 41),
                'deleted_at' => null,
            ],
            [
                'id' => 61,
                'location' => 'header',
                'title' => 'Vehicular Exhaust',
                'title_hi' => 'वाहनों का धुआँ',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/standards/vehicular-exhaust',
                'icon_png' => null,
                'parent_id' => 3,
                'order' => 4,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 10, 27, 17, 21, 23),
                'updated_at' => Carbon::create(2025, 12, 4, 22, 55, 49),
                'deleted_at' => null,
            ],
            [
                'id' => 62,
                'location' => 'header',
                'title' => 'Bio Medical Incinerators',
                'title_hi' => 'जैव चिकित्सा भस्मक',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/standards/bio-medical-incinerators',
                'icon_png' => null,
                'parent_id' => 3,
                'order' => 5,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 10, 27, 17, 29, 8),
                'updated_at' => Carbon::create(2025, 12, 4, 22, 55, 49),
                'deleted_at' => null,
            ],
            [
                'id' => 63,
                'location' => 'header',
                'title' => 'Common HW Incinerators',
                'title_hi' => 'सामान्य एचडब्ल्यू भस्मक',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/standards/Common-hw-incinerators',
                'icon_png' => null,
                'parent_id' => 3,
                'order' => 6,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 10, 27, 17, 51, 4),
                'updated_at' => Carbon::create(2025, 12, 4, 22, 55, 49),
                'deleted_at' => null,
            ],
            [
                'id' => 65,
                'location' => 'inner-pages',
                'title' => 'Noise Limits for Vehicles & Airport',
                'title_hi' => 'Noise Limits for Vehicles & Airport',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/standards/noise/noise-limits-for-vehicles&airport',
                'icon_png' => null,
                'parent_id' => 21,
                'order' => 0,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 10, 28, 14, 0, 32),
                'updated_at' => Carbon::create(2025, 10, 28, 14, 51, 21),
                'deleted_at' => null,
            ],
            [
                'id' => 66,
                'location' => 'inner-pages',
                'title' => 'Noise Limits for Generator Set',
                'title_hi' => 'Noise Limits for Generator Set',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/standards/noise/noise-limits-for-generator-set',
                'icon_png' => null,
                'parent_id' => 21,
                'order' => 1,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 10, 28, 14, 1, 0),
                'updated_at' => Carbon::create(2025, 10, 28, 14, 52, 37),
                'deleted_at' => null,
            ],
            [
                'id' => 67,
                'location' => 'inner-pages',
                'title' => 'Implementation of Noise Rules',
                'title_hi' => 'Implementation of Noise Rules',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/standards/noise/implementation-of-noise-rules',
                'icon_png' => null,
                'parent_id' => 21,
                'order' => 2,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 10, 28, 14, 1, 20),
                'updated_at' => Carbon::create(2025, 10, 28, 14, 53, 54),
                'deleted_at' => null,
            ],
            [
                'id' => 68,
                'location' => 'inner-pages',
                'title' => 'Fire Crackers Noise Rules',
                'title_hi' => 'Fire Crackers Noise Rules',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/standards/noise/fire-crackers-noise-rules',
                'icon_png' => null,
                'parent_id' => 21,
                'order' => 3,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 10, 28, 14, 1, 40),
                'updated_at' => Carbon::create(2025, 10, 28, 14, 55, 0),
                'deleted_at' => null,
            ],
            [
                'id' => 69,
                'location' => 'header',
                'title' => 'Generator Set',
                'title_hi' => 'Generator Set',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/standards/generator-set',
                'icon_png' => null,
                'parent_id' => 3,
                'order' => 7,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 10, 28, 15, 55, 25),
                'updated_at' => Carbon::create(2025, 12, 4, 22, 55, 49),
                'deleted_at' => null,
            ],
            [
                'id' => 70,
                'location' => 'inner-pages',
                'title' => 'Genset Notifications',
                'title_hi' => 'Genset Notifications',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/standards/generator-set/denset-notification',
                'icon_png' => null,
                'parent_id' => 69,
                'order' => 0,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 10, 28, 15, 57, 36),
                'updated_at' => Carbon::create(2025, 10, 28, 15, 57, 36),
                'deleted_at' => null,
            ],
            [
                'id' => 71,
                'location' => 'inner-pages',
                'title' => 'Guidelines',
                'title_hi' => 'Guidelines',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/standards/generator-set/guidelines',
                'icon_png' => null,
                'parent_id' => 69,
                'order' => 1,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 10, 28, 15, 58, 38),
                'updated_at' => Carbon::create(2025, 10, 28, 15, 58, 38),
                'deleted_at' => null,
            ],
            [
                'id' => 72,
                'location' => 'header',
                'title' => 'Industry Specific Standards',
                'title_hi' => 'Industry Specific Standards',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '/standards/Industry-specific-standards',
                'icon_png' => null,
                'parent_id' => 3,
                'order' => 8,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 11, 5, 19, 3, 17),
                'updated_at' => Carbon::create(2025, 12, 4, 22, 55, 49),
                'deleted_at' => null,
            ],
            [
                'id' => 76,
                'location' => 'header',
                'title' => 'Suo-moto disclosure of CPCB Information',
                'title_hi' => 'CPCB जानकारी का स्वतः प्रकटीकरण',
                'type' => 'URL',
                'file_name' => null,
                'file_name_hi' => null,
                'url' => '#',
                'icon_png' => 'FileText',
                'parent_id' => 2,
                'order' => 7,
                'permission_name' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::create(2025, 12, 10, 4, 0, 10),
                'updated_at' => Carbon::create(2025, 12, 16, 6, 49, 22),
                'deleted_at' => null,
            ],
        ];

        foreach ($menus as $menu) {
            DB::table('menus')->updateOrInsert(
                ['id' => $menu['id']],
                $menu
            );
        }
    }





    //     DO $$
    // DECLARE
    //     row RECORD;
    // BEGIN
    //     FOR row IN (
    //         SELECT table_name, column_name, column_default
    //         FROM information_schema.columns
    //         WHERE column_default LIKE 'nextval%'
    //         AND table_schema = 'public'
    //     )
    //     LOOP
    //         EXECUTE 'SELECT setval(''' ||
    //                 regexp_replace(row.column_default, 'nextval\(''(.+)''::regclass\)', '\1') ||
    //                 ''', COALESCE((SELECT MAX(' || row.column_name || ') FROM ' || row.table_name || '), 1))';
    //     END LOOP;
    // END $$;
}
